### ISSUE TITLE
More test examples

### ISSUE THREAD

**Issue by Nevon** [hubot-scripts/hubot-example#5]
The examples provided are quite sparse. It would be nice to include some examples of how to verify that the bot is sending correct replies, etc.

**Comment by technicalpickles** [comment]
Sorry for missing this, I wasn't watching the repository until recently :sweat: 

I've intend to [deprecate this repository](https://github.com/hubot-scripts/hubot-example/issues/9), since we have a [script generator] now. I've filed  https://github.com/github/generator-hubot/issues/45 to get better testing examples in place for it too.
